[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/exe/initialize.sh startup"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
healthCheckPath = "/"
healthCheckTimeout = 50
healthCheckInterval = 10

[[ports]]
port = 80
internalPort = 80
protocol = "tcp"